const continents = [
    {"code":"AN", "name":"Antarctica"},
    {"code":"AF", "name":"Africa"},
    {"code":"AS", "name":"Asia"},
    {"code":"EU", "name":"Europe"},
    {"code":"NO", "name":"North america"},
    {"code":"OC", "name":"Oceania"},
    {"code":"SO", "name":"South america"},
]


var continentCountriesList = [
    { 'continent': 'AN', 'names': [
            {"code":"AQ", "name":"Antarctica"},
            {"code":"BV", "name":"Bouvet Island (Bouvetoya)"},
            {"code":"TF", "name":"French Southern Territories"},
            {"code":"HM", "name":"Heard Island and McDonald Islands"},
            {"code":"GS", "name":"South Georgia and the South Sandwich Islands"},
    ] },
    { 'continent': 'AF', 'names': [
            {"code":"DZ", "name":"Algeria"},
            {"code":"AO", "name":"Angola"},
            {"code":"BJ", "name":"Benin"},
            {"code":"BW", "name":"Botswana"},
            {"code":"BF", "name":"Burkina Faso"},
            {"code":"BI", "name":"Burundi"},
            {"code":"CM", "name":"Cameroon"},
            {"code":"CV", "name":"Cape Verde"},
            {"code":"CF", "name":"Central African Republic"},
            {"code":"TD", "name":"Chad"},
            {"code":"KM", "name":"Comoros the"},
            {"code":"CD", "name":"Congo"},
            {"code":"CG", "name":"Congo the"},
            {"code":"CI", "name":"Cote d'Ivoire"},
            {"code":"DJ", "name":"Djibouti"},
            {"code":"EG", "name":"Egypt", "nameProvinceRegion": "governorates","provinces":[
                    {"code":"EG-1", "name":"6th of October"},
                    {"code":"EG-2", "name":"Al Sharqia"},
                    {"code":"EG-3", "name":"Alexandria"},
                    {"code":"EG-4", "name":"Aswan"},
                    {"code":"EG-5", "name":"Asyut"},
                    {"code":"EG-6", "name":"Beheira"},
                    {"code":"EG-7", "name":"Beni Suef"},
                    {"code":"EG-8", "name":"Cairo"},
                    {"code":"EG-9", "name":"Dakahlia"},
                    {"code":"EG-10", "name":"Damietta"},
                    {"code":"EG-11", "name":"Faiyum"},
                    {"code":"EG-12", "name":"Gharbia"},
                    {"code":"EG-13", "name":"Giza"},
                    {"code":"EG-14", "name":"Helwan"},
                    {"code":"EG-15", "name":"Ismailia"},
                    {"code":"EG-16", "name":"Kafr el-Sheikh"},
                    {"code":"EG-17", "name":"Luxor"},
                    {"code":"EG-18", "name":"Matrouh"},
                    {"code":"EG-19", "name":"Minya"},
                    {"code":"EG-20", "name":"Monufia"},
                    {"code":"EG-21", "name":"New Valley"},
                    {"code":"EG-22", "name":"North Sinai"},
                    {"code":"EG-23", "name":"Port Said"},
                    {"code":"EG-24", "name":"Qalyubia"},
                    {"code":"EG-25", "name":"Qena"},
                    {"code":"EG-26", "name":"Red Sea"},
                    {"code":"EG-27", "name":"Sohag"},
                    {"code":"EG-28", "name":"South Sinai"},
                    {"code":"EG-29", "name":"Suez"},
                    ]},
            {"code":"ER", "name":"Eritrea"},
            {"code":"ET", "name":"Ethiopia"},
            {"code":"GA", "name":"Gabon"},
            {"code":"GM", "name":"Gambia the"},
            {"code":"GH", "name":"Ghana"},
            {"code":"GN", "name":"Guinea"},
            {"code":"GW", "name":"Guinea-Bissau"},
            {"code":"GQ", "name":"Equatorial Guinea"},
            {"code":"KE", "name":"Kenya"},
            {"code":"LR", "name":"Liberia"},
            {"code":"LS", "name":"Lesotho"},
            {"code":"LY", "name":"Libyan Arab Jamahiriya"},
            {"code":"MA", "name":"Morocco"},
            {"code":"MG", "name":"Madagascar"},
            {"code":"ML", "name":"Mali"},
            {"code":"MR", "name":"Mauritania"},
            {"code":"MU", "name":"Mauritius"},
            {"code":"MW", "name":"Malawi"},
            {"code":"YT", "name":"Mayotte"},
            {"code":"MZ", "name":"Mozambique"},
            {"code":"NA", "name":"Namibia"},
            {"code":"NE", "name":"Niger"},
            {"code":"NG", "name":"Nigeria", "nameProvinceRegion": "states","provinces":[
                            {"code":"NG-0", "name":"Abuja"},{"code":"NG-1", "name":"Abia"},{"code":"NG-2", "name":"Adamawa"},{"code":"NG-3", "name":"Akwa Ibom"},{"code":"NG-4", "name":"Anambra"},{"code":"NG-5", "name":"Bauchi"},{"code":"NG-6", "name":"Bayelsa"},{"code":"NG-7", "name":"Benue"},{"code":"NG-8", "name":"Borno"},{"code":"NG-9", "name":"Cross River"},{"code":"NG-10", "name":"Delta"},{"code":"NG-11", "name":"Ebonyi"},{"code":"NG-12", "name":"Edo"},{"code":"NG-13", "name":"Ekiti"},{"code":"NG-14", "name":"Enugu"},{"code":"NG-15", "name":"Gombe"},{"code":"NG-16", "name":"Imo"},{"code":"NG-17", "name":"Jigawa"},{"code":"NG-18", "name":"Kaduna"},{"code":"NG-19", "name":"Kano"},{"code":"NG-20", "name":"Katsina"},{"code":"NG-21", "name":"Kebbi"},{"code":"NG-22", "name":"Kogi"},{"code":"NG-23", "name":"Kwara"},{"code":"NG-24", "name":"Lagos"},{"code":"NG-25", "name":"Nassarawa"},{"code":"NG-26", "name":"Niger"},{"code":"NG-27", "name":"Ogun"},{"code":"NG-28", "name":"Ondo"},{"code":"NG-29", "name":"Osun"},{"code":"NG-30", "name":"Oyo"},{"code":"NG-31", "name":"Plateau"},{"code":"NG-32", "name":"Rivers"},{"code":"NG-33", "name":"Sokoto"},{"code":"NG-34", "name":"Taraba"},{"code":"NG-35", "name":"Yobe"},{"code":"NG-36", "name":"Zamfara"},
                    ]},
            {"code":"RE", "name":"Reunion"},
            {"code":"RW", "name":"Rwanda"},
            {"code":"SH", "name":"Saint Helena"},
            {"code":"ST", "name":"Sao Tome and Principe"},
            {"code":"SN", "name":"Senegal"},
            {"code":"SC", "name":"Seychelles"},
            {"code":"SL", "name":"Sierra Leone"},
            {"code":"SO", "name":"Somalia, Somali Republic"},
            {"code":"ZA", "name":"South Africa", "nameProvinceRegion": "provinces","provinces":[
                            {"code":"ZA-0", "name":"Eastern Cape"},{"code":"ZA-1", "name":"Free State"},{"code":"ZA-2", "name":"Gauteng"},{"code":"ZA-3", "name":"KwaZulu-Natal"},{"code":"ZA-4", "name":"Limpopo"},{"code":"ZA-5", "name":"Mpumalanga"},{"code":"ZA-6", "name":"North West"},{"code":"ZA-7", "name":"Northern Cape"},{"code":"ZA-8", "name":"Western Cape"},
                    ]},
            {"code":"SD", "name":"Sudan"},
            {"code":"SZ", "name":"Swaziland"},
            {"code":"TZ", "name":"Tanzania"},
            {"code":"TG", "name":"Togo"},
            {"code":"TN", "name":"Tunisia"},
            {"code":"UG", "name":"Uganda"},
            {"code":"EH", "name":"Western Sahara"},
            {"code":"ZM", "name":"Zambia"},
            {"code":"ZW", "name":"Zimbabwe"},
    ] },
    { 'continent': 'AS', 'names': [

            {"code":"AF", "name":"Afghanistan"},
            {"code":"AM", "name":"Armenia"},
            {"code":"AP", "name":"AP"},
            {"code":"AZ", "name":"Azerbaijan"},
            {"code":"BH", "name":"Bahrain"},
            {"code":"BD", "name":"Bangladesh"},
            {"code":"BT", "name":"Bhutan"},
            {"code":"IO", "name":"British Indian Ocean Territory (Chagos Archipelago)"},
            {"code":"BN", "name":"Brunei Darussalam"},
            {"code":"KH", "name":"Cambodia"},
            {"code":"CC", "name":"Cocos (Keeling) Islands"},
            {"code":"CN", "name":"China", "nameProvinceRegion": "provinces","provinces":[
                            {"code":"CN-0", "name":"Anhui"},{"code":"CN-1", "name":"Beijing"},{"code":"CN-2", "name":"Chongqing"},{"code":"CN-3", "name":"Fujian"},{"code":"CN-4", "name":"Gansu"},{"code":"CN-5", "name":"Guangdong"},{"code":"CN-6", "name":"Guangxi"},{"code":"CN-7", "name":"Guizhou"},{"code":"CN-8", "name":"Hainan"},{"code":"CN-9", "name":"Hebei"},{"code":"CN-10", "name":"Heilongjiang"},{"code":"CN-11", "name":"Henan"},{"code":"CN-12", "name":"Hubei"},{"code":"CN-13", "name":"Hunan"},{"code":"CN-14", "name":"Inner Mongolia"},{"code":"CN-15", "name":"Jiangsu"},{"code":"CN-16", "name":"Jiangxi"},{"code":"CN-17", "name":"Jilin"},{"code":"CN-18", "name":"Liaoning"},{"code":"CN-19", "name":"Ningxia"},{"code":"CN-20", "name":"Qinghai"},{"code":"CN-21", "name":"Shaanxi"},{"code":"CN-22", "name":"Shandong"},{"code":"CN-23", "name":"Shanghai"},{"code":"CN-24", "name":"Shanxi"},{"code":"CN-25", "name":"Sichuan"},{"code":"CN-26", "name":"Tianjin"},{"code":"CN-27", "name":"Tibet"},{"code":"CN-28", "name":"Yunnan"},{"code":"CN-29", "name":"Zhejiang"},{"code":"CN-30", "name":"Xinjiang"},
                ]},
            {"code":"CX", "name":"Christmas Island"},
            {"code":"CY", "name":"Cyprus"},
            {"code":"GE", "name":"Georgia"},
            {"code":"HK", "name":"Hong Kong", "nameProvinceRegion": "regions","provinces":[
                            {"code":"HK-0", "name":"Hong Kong Island"},{"code":"HK-1", "name":"Kowloon"},{"code":"HK-2", "name":"New Territories"},
                ]},
            {"code":"IN", "name":"India", "nameProvinceRegion": "states","provinces":[
                            {"code":"IN-0", "name":"Andaman and Nicobar Islands"},{"code":"IN-1", "name":"Andhra Pradesh"},{"code":"IN-2", "name":"Arunachal Pradesh"},{"code":"IN-3", "name":"Assam"},{"code":"IN-4", "name":"Bihar"},{"code":"IN-5", "name":"Chandigarh"},{"code":"IN-6", "name":"Chhattisgarh"},{"code":"IN-7", "name":"Dadra and Nagar Haveli"},{"code":"IN-8", "name":"Daman and Diu"},{"code":"IN-9", "name":"Delhi"},{"code":"IN-10", "name":"Goa"},{"code":"IN-11", "name":"Gujarat"},{"code":"IN-12", "name":"Haryana"},{"code":"IN-13", "name":"Himachal Pradesh"},{"code":"IN-14", "name":"Jammu and Kashmir"},{"code":"IN-15", "name":"Jharkhand"},{"code":"IN-16", "name":"Karnataka"},{"code":"IN-17", "name":"Kerala"},{"code":"IN-18", "name":"Ladakh"},{"code":"IN-19", "name":"Lakshadweep"},{"code":"IN-20", "name":"Madhya Pradesh"},{"code":"IN-21", "name":"Maharashtra"},{"code":"IN-22", "name":"Manipur"},{"code":"IN-23", "name":"Meghalaya"},{"code":"IN-24", "name":"Mizoram"},{"code":"IN-25", "name":"Nagaland"},{"code":"IN-26", "name":"Odisha"},{"code":"IN-27", "name":"Puducherry"},{"code":"IN-28", "name":"Punjab"},{"code":"IN-29", "name":"Rajasthan"},{"code":"IN-30", "name":"Sikkim"},{"code":"IN-31", "name":"Tamil Nadu"},{"code":"IN-32", "name":"Telangana"},{"code":"IN-33", "name":"Tripura"},{"code":"IN-34", "name":"Uttar Pradesh"},{"code":"IN-35", "name":"Uttarakhand"},{"code":"IN-36", "name":"West Bengal"},
                ]},
            {"code":"ID", "name":"Indonesia", "nameProvinceRegion": "provinces","provinces":[
                            {"code":"ID-0", "name":"Andaman and Nicobar Islands"},{"code":"ID-1", "name":"Aceh"},{"code":"ID-2", "name":"Bali"},{"code":"ID-3", "name":"Bangka–Belitung Islands"},{"code":"ID-4", "name":"Banten"},{"code":"ID-5", "name":"Bengkulu"},{"code":"ID-6", "name":"Gorontalo"},{"code":"ID-7", "name":"Jakarta"},{"code":"ID-8", "name":"Jambi"},{"code":"ID-9", "name":"West Java"},{"code":"ID-10", "name":"Central Java"},{"code":"ID-11", "name":"East Java"},{"code":"ID-12", "name":"West Kalimantan"},{"code":"ID-13", "name":"South Kalimantan"},{"code":"ID-14", "name":"Central Kalimantan"},{"code":"ID-15", "name":"East Kalimantan"},{"code":"ID-16", "name":"North Kalimantan"},{"code":"ID-17", "name":"Riau Islands"},{"code":"ID-18", "name":"Lampung"},{"code":"ID-19", "name":"Maluku"},{"code":"ID-20", "name":"North Maluku"},{"code":"ID-21", "name":"North Sumatra"},{"code":"ID-22", "name":"West Nusa Tenggara"},{"code":"ID-23", "name":"East Nusa Tenggara"},{"code":"ID-24", "name":"Papua"},{"code":"ID-25", "name":"West Papua"},{"code":"ID-26", "name":"Riau"},{"code":"ID-27", "name":"South Sumatra"},{"code":"ID-28", "name":"West Sulawesi"},{"code":"ID-29", "name":"South Sulawesi"},{"code":"ID-30", "name":"Central Sulawesi"},{"code":"ID-31", "name":"Southeast Sulawesi"},{"code":"ID-32", "name":"North Sulawesi"},{"code":"ID-33", "name":"West Sumatra"},{"code":"ID-34", "name":"Yogyakarta"},
                ]},
            {"code":"IL", "name":"Israel"},
            {"code":"IQ", "name":"Iraq"},
            {"code":"IR", "name":"Iran"},
            {"code":"JO", "name":"Jordan"},
            {"code":"JP", "name":"Japan", "nameProvinceRegion": "prefectures","provinces":[
                            {"code":"JP-0", "name":"Hokkaido"},{"code":"JP-1", "name":"Aomori"},{"code":"JP-2", "name":"Iwate"},{"code":"JP-3", "name":"Miyagi"},{"code":"JP-4", "name":"Akita"},{"code":"JP-5", "name":"Yamagata"},{"code":"JP-6", "name":"Fukushima"},{"code":"JP-7", "name":"Ibaraki"},{"code":"JP-8", "name":"Tochigi"},{"code":"JP-9", "name":"Gunma"},{"code":"JP-10", "name":"Saitama"},{"code":"JP-11", "name":"Chiba"},{"code":"JP-12", "name":"Tokyo"},{"code":"JP-13", "name":"Kanagawa"},{"code":"JP-14", "name":"Niigata"},{"code":"JP-15", "name":"Toyama"},{"code":"JP-16", "name":"Ishikawa"},{"code":"JP-17", "name":"Fukui"},{"code":"JP-18", "name":"Yamanashi"},{"code":"JP-19", "name":"Nagano"},{"code":"JP-20", "name":"Gifu"},{"code":"JP-21", "name":"Shizuoka"},{"code":"JP-22", "name":"Aichi"},{"code":"JP-23", "name":"Mie"},{"code":"JP-24", "name":"Shiga"},{"code":"JP-25", "name":"Kyoto"},{"code":"JP-26", "name":"Osaka"},{"code":"JP-27", "name":"Hyogo"},{"code":"JP-28", "name":"Nara"},{"code":"JP-29", "name":"Wakayama"},{"code":"JP-30", "name":"Tottori"},{"code":"JP-31", "name":"Shimane"},{"code":"JP-32", "name":"Okayama"},{"code":"JP-33", "name":"Hiroshima"},{"code":"JP-34", "name":"Yamaguchi"},{"code":"JP-35", "name":"Tokushima"},{"code":"JP-36", "name":"Kagawa"},{"code":"JP-37", "name":"Ehime"},{"code":"JP-38", "name":"Kochi"},{"code":"JP-39", "name":"Fukuoka"},{"code":"JP-40", "name":"Saga"},{"code":"JP-41", "name":"Nagasaki"},{"code":"JP-42", "name":"Kumamoto"},{"code":"JP-43", "name":"Oita"},{"code":"JP-44", "name":"Miyazaki"},{"code":"JP-45", "name":"Kagoshima"},{"code":"JP-46", "name":"Okinawa"},
                    ]},
            {"code":"KZ", "name":"Kazakhstan"},
            {"code":"KR", "name":"Korea South", "nameProvinceRegion": "provinces","provinces":[
                            {"code":"KR-0", "name":"Busan"},{"code":"KR-1", "name":"North Chungcheong"},{"code":"KR-2", "name":"South Chungcheong"},{"code":"KR-3", "name":"Daegu"},{"code":"KR-4", "name":"Daejeon"},{"code":"KR-5", "name":"Gangwon"},{"code":"KR-6", "name":"Gwangju City"},{"code":"KR-7", "name":"North Gyeongsang"},{"code":"KR-8", "name":"Gyeonggi"},{"code":"KR-9", "name":"South Gyeongsang"},{"code":"KR-10", "name":"Incheon"},{"code":"KR-11", "name":"Jeju"},{"code":"KR-12", "name":"North Jeolla"},{"code":"KR-13", "name":"South Jeolla"},{"code":"KR-14", "name":"Sejong"},{"code":"KR-15", "name":"Seoul"},{"code":"KR-16", "name":"Ulsan"},
                    ]},
            {"code":"KG", "name":"Kyrgyz Republic"},
            {"code":"KW", "name":"Kuwait"},
            {"code":"LA", "name":"Lao"},
            {"code":"LB", "name":"Lebanon"},
            {"code":"MO", "name":"Macao"},
            {"code":"MV", "name":"Maldives"},
            {"code":"MY", "name":"Malaysia", "nameProvinceRegion": "territories","provinces":[
                            {"code":"MY-0", "name":"Johor"},{"code":"MY-1", "name":"Kedah"},{"code":"MY-2", "name":"Kelantan"},{"code":"MY-3", "name":"Kuala Lumpur"},{"code":"MY-4", "name":"Labuan"},{"code":"MY-5", "name":"Malacca"},{"code":"MY-6", "name":"Negeri Sembilan"},{"code":"MY-7", "name":"Pahang"},{"code":"MY-8", "name":"Penang"},{"code":"MY-9", "name":"Perak"},{"code":"MY-10", "name":"Perlis"},{"code":"MY-11", "name":"Putrajaya"},{"code":"MY-12", "name":"Sabah"},{"code":"MY-13", "name":"Sarawak"},{"code":"MY-14", "name":"Selangor"},{"code":"MY-15", "name":"Terengganu"},
                    ]},
            {"code":"MN", "name":"Mongolia"},
            {"code":"MM", "name":"Myanmar"},
            {"code":"NP", "name":"Nepal"},
            {"code":"OM", "name":"Oman"},
            {"code":"PK", "name":"Pakistan"},
            {"code":"PS", "name":"Palestinian Territory"},
            {"code":"PH", "name":"Philippines", "nameProvinceRegion": "regions","provinces":[
                            {"code":"PH-0", "name":"Abra"},{"code":"PH-1", "name":"Agusan del Norte"},{"code":"PH-2", "name":"Agusan del Sur"},{"code":"PH-3", "name":"Aklan"},{"code":"PH-4", "name":"Albay"},{"code":"PH-5", "name":"Antique"},{"code":"PH-6", "name":"Apayao"},{"code":"PH-7", "name":"Aurora"},{"code":"PH-8", "name":"Basilan"},{"code":"PH-9", "name":"Bataan"},{"code":"PH-10", "name":"Batanes"},{"code":"PH-11", "name":"Batangas"},{"code":"PH-12", "name":"Benguet"},{"code":"PH-13", "name":"Biliran"},{"code":"PH-14", "name":"Bohol"},{"code":"PH-15", "name":"Bukidnon"},{"code":"PH-16", "name":"Bulacan"},{"code":"PH-17", "name":"Cagayan"},{"code":"PH-18", "name":"Camarines Norte"},{"code":"PH-19", "name":"Camarines Sur"},{"code":"PH-20", "name":"Camiguin"},{"code":"PH-21", "name":"Capiz"},{"code":"PH-22", "name":"Catanduanes"},{"code":"PH-23", "name":"Cavite"},{"code":"PH-24", "name":"Cebu"},{"code":"PH-25", "name":"Cotabato"},{"code":"PH-26", "name":"Davao Occidental"},{"code":"PH-27", "name":"Davao Oriental"},{"code":"PH-28", "name":"Compostela Valley"},{"code":"PH-29", "name":"Davao del Norte"},{"code":"PH-30", "name":"Davao del Sur"},{"code":"PH-31", "name":"Dinagat Islands"},{"code":"PH-32", "name":"Eastern Samar"},{"code":"PH-33", "name":"Guimaras"},{"code":"PH-34", "name":"Ifugao"},{"code":"PH-35", "name":"Ilocos Norte"},{"code":"PH-36", "name":"Ilocos Sur"},{"code":"PH-37", "name":"Iloilo"},{"code":"PH-38", "name":"Isabela"},{"code":"PH-39", "name":"Kalinga"},{"code":"PH-40", "name":"La Union"},{"code":"PH-41", "name":"Laguna"},{"code":"PH-42", "name":"Lanao del Norte"},{"code":"PH-43", "name":"Lanao del Sur"},{"code":"PH-44", "name":"Leyte"},{"code":"PH-45", "name":"Maguindanao"},{"code":"PH-46", "name":"Marinduque"},{"code":"PH-47", "name":"Masbate"},{"code":"PH-48", "name":"Metro Manila"},{"code":"PH-49", "name":"Misamis Occidental"},{"code":"PH-50", "name":"Misamis Oriental"},{"code":"PH-51", "name":"Mountain"},{"code":"PH-52", "name":"Negros Occidental"},{"code":"PH-53", "name":"Negros Oriental"},{"code":"PH-54", "name":"Northern Samar"},{"code":"PH-55", "name":"Nueva Ecija"},{"code":"PH-56", "name":"Nueva Vizcaya"},{"code":"PH-57", "name":"Occidental Mindoro"},{"code":"PH-58", "name":"Oriental Mindoro"},{"code":"PH-59", "name":"Palawan"},{"code":"PH-60", "name":"Pampanga"},{"code":"PH-61", "name":"Pangasinan"},{"code":"PH-62", "name":"Quezon"},{"code":"PH-63", "name":"Quirino"},{"code":"PH-64", "name":"Rizal"},{"code":"PH-65", "name":"Romblon"},{"code":"PH-66", "name":"Samar"},{"code":"PH-67", "name":"Sarangani"},{"code":"PH-68", "name":"Siquijor"},{"code":"PH-69", "name":"Sorsogon"},{"code":"PH-70", "name":"South Cotabato"},{"code":"PH-71", "name":"Southern Leyte"},{"code":"PH-72", "name":"Sultan Kudarat"},{"code":"PH-73", "name":"Sulu"},{"code":"PH-74", "name":"Surigao del Norte"},{"code":"PH-75", "name":"Surigao del Sur"},{"code":"PH-76", "name":"Tarlac"},{"code":"PH-77", "name":"Tawi-Tawi"},{"code":"PH-78", "name":"Zambales"},{"code":"PH-79", "name":"Zamboanga Sibugay"},{"code":"PH-80", "name":"Zamboanga del Norte"},{"code":"PH-81", "name":"Zamboanga del Sur"},
                    ]},
            {"code":"QA", "name":"Qatar"},
            {"code":"SA", "name":"Saudi Arabia"},
            {"code":"SG", "name":"Singapore"},
            {"code":"LK", "name":"Sri Lanka"},
            {"code":"SY", "name":"Syrian Arab Republic"},
            {"code":"TW", "name":"Taiwan"},
            {"code":"TJ", "name":"Tajikistan"},
            {"code":"TH", "name":"Thailand", "nameProvinceRegion": "provinces","provinces":[
                            {"code":"TH-0", "name":"Amnat Charoen"},{"code":"TH-1", "name":"Ang Thong"},{"code":"TH-2", "name":"Bangkok"},{"code":"TH-3", "name":"Bueng Kan"},{"code":"TH-4", "name":"Buri Ram"},{"code":"TH-5", "name":"Chachoengsao"},{"code":"TH-6", "name":"Chai Nat"},{"code":"TH-7", "name":"Chaiyaphum"},{"code":"TH-8", "name":"Chanthaburi"},{"code":"TH-9", "name":"Chiang Mai"},{"code":"TH-10", "name":"Chiang Rai"},{"code":"TH-11", "name":"Chon Buri"},{"code":"TH-12", "name":"Chumphon"},{"code":"TH-13", "name":"Kalasin"},{"code":"TH-14", "name":"Kamphaeng Phet"},{"code":"TH-15", "name":"Kanchanaburi"},{"code":"TH-16", "name":"Khon Kaen"},{"code":"TH-17", "name":"Krabi"},{"code":"TH-18", "name":"Lampang"},{"code":"TH-19", "name":"Lamphun"},{"code":"TH-20", "name":"Loei"},{"code":"TH-21", "name":"Lopburi"},{"code":"TH-22", "name":"Mae Hong Son"},{"code":"TH-23", "name":"Maha Sarakham"},{"code":"TH-24", "name":"Mukdahan"},{"code":"TH-25", "name":"Nakhon Nayok"},{"code":"TH-26", "name":"Nakhon Pathom"},{"code":"TH-27", "name":"Nakhon Phanom"},{"code":"TH-28", "name":"Nakhon Ratchasima"},{"code":"TH-29", "name":"Nakhon Sawan"},{"code":"TH-30", "name":"Nakhon Si Thammarat"},{"code":"TH-31", "name":"Nan"},{"code":"TH-32", "name":"Narathiwat"},{"code":"TH-33", "name":"Nong Bua Lam Phu"},{"code":"TH-34", "name":"Nong Khai"},{"code":"TH-35", "name":"Nonthaburi"},{"code":"TH-36", "name":"Pathum Thani"},{"code":"TH-37", "name":"Pattani"},{"code":"TH-38", "name":"Pattaya"},{"code":"TH-39", "name":"Phang Nga"},{"code":"TH-40", "name":"Phatthalung"},{"code":"TH-41", "name":"Phayao"},{"code":"TH-42", "name":"Phetchabun"},{"code":"TH-43", "name":"Phetchaburi"},{"code":"TH-44", "name":"Phichit"},{"code":"TH-45", "name":"Phitsanulok"},{"code":"TH-46", "name":"Phra Nakhon Si Ayutthaya"},{"code":"TH-47", "name":"Phrae"},{"code":"TH-48", "name":"Phuket"},{"code":"TH-49", "name":"Prachin Buri"},{"code":"TH-50", "name":"Prachuap Khiri Khan"},{"code":"TH-51", "name":"Ranong"},{"code":"TH-52", "name":"Ratchaburi"},{"code":"TH-53", "name":"Rayong"},{"code":"TH-54", "name":"Roi Et"},{"code":"TH-55", "name":"Sa Kaeo"},{"code":"TH-56", "name":"Sakon Nakhon"},{"code":"TH-57", "name":"Samut Prakan"},{"code":"TH-58", "name":"Samut Sakhon"},{"code":"TH-59", "name":"Samut Songkhram"},{"code":"TH-60", "name":"Saraburi"},{"code":"TH-61", "name":"Satun"},{"code":"TH-62", "name":"Sing Buri"},{"code":"TH-63", "name":"Si Sa Ket"},{"code":"TH-64", "name":"Songkhla"},{"code":"TH-65", "name":"Sukhothai"},{"code":"TH-66", "name":"Suphanburi"},{"code":"TH-67", "name":"Surat Thani"},{"code":"TH-68", "name":"Surin"},{"code":"TH-69", "name":"Tak"},{"code":"TH-70", "name":"Trang"},{"code":"TH-71", "name":"Trat"},{"code":"TH-72", "name":"Ubon Ratchathani"},{"code":"TH-73", "name":"Udon Thani"},{"code":"TH-74", "name":"Uthai Thani"},{"code":"TH-75", "name":"Uttaradit"},{"code":"TH-76", "name":"Yala"},{"code":"TH-77", "name":"Yasothon"},
                    ]},
            {"code":"TL", "name":"Timor-Leste"},
            {"code":"TM", "name":"Turkmenistan"},
            {"code":"AE", "name":"United Arab Emirates", "nameProvinceRegion": "emirates","provinces":[
                            {"code":"AE-0", "name":"Abu Dhabi"},{"code":"AE-1", "name":"Ajman"},{"code":"AE-2", "name":"Dubai"},{"code":"AE-3", "name":"Fujairah"},{"code":"AE-4", "name":"Ras al-Khaimah"},{"code":"AE-5", "name":"Sharjah"},{"code":"AE-6", "name":"Umm al-Quwain"},
                    ]},
            {"code":"UZ", "name":"Uzbekistan"},
            {"code":"VN", "name":"Vietnam"},
            {"code":"YE", "name":"Yemen"}
        ] },
    { 'continent': 'EU', 'names': [
            {"code":"AX", "name":"Aland Islands"},
            {"code":"AL", "name":"Albania"},
            {"code":"AD", "name":"Andorra"},
            {"code":"AT", "name":"Austria"},
            {"code":"BY", "name":"Belarus"},
            {"code":"BE", "name":"Belgium"},
            {"code":"BA", "name":"Bosnia and Herzegovina"},
            {"code":"BG", "name":"Bulgaria"},
            {"code":"HR", "name":"Croatia"},
            {"code":"CZ", "name":"Czech Republic"},
            {"code":"DK", "name":"Denmark"},
            {"code":"EE", "name":"Estonia"},
            {"code":"FO", "name":"Faroe Islands"},
            {"code":"FI", "name":"Finland"},
            {"code":"FR", "name":"France, French Republic"},
            {"code":"DE", "name":"Germany"},
            {"code":"GI", "name":"Gibraltar"},
            {"code":"GR", "name":"Greece"},
            {"code":"GG", "name":"Guernsey"},
            {"code":"HU", "name":"Hungary"},
            {"code":"IS", "name":"Iceland"},
            {"code":"IM", "name":"Isle of Man"},
            {"code":"IT", "name":"Italy", "nameProvinceRegion": "provinces","provinces":[
                            {"code":"IT-0", "name":"Agrigento"},{"code":"IT-1", "name":"Alessandria"},{"code":"IT-2", "name":"Ancona"},{"code":"IT-3", "name":"Aosta"},{"code":"IT-4", "name":"Ascoli Piceno"},{"code":"IT-5", "name":"L'Aquila"},{"code":"IT-6", "name":"Arezzo"},{"code":"IT-7", "name":"Asti"},{"code":"IT-8", "name":"Avellino"},{"code":"IT-9", "name":"Bari"},{"code":"IT-10", "name":"Bergamo"},{"code":"IT-11", "name":"Biella"},{"code":"IT-12", "name":"Belluno"},{"code":"IT-13", "name":"Benevento"},{"code":"IT-14", "name":"Bologna"},{"code":"IT-15", "name":"Brindisi"},{"code":"IT-16", "name":"Brescia"},{"code":"IT-17", "name":"Barletta-Andria-Trani"},{"code":"IT-18", "name":"Bolzano"},{"code":"IT-19", "name":"Cagliari"},{"code":"IT-20", "name":"Campobasso"},{"code":"IT-21", "name":"Caserta"},{"code":"IT-22", "name":"Chieti"},{"code":"IT-23", "name":"Carbonia-Iglesias"},{"code":"IT-24", "name":"Caltanissetta"},{"code":"IT-25", "name":"Cuneo"},{"code":"IT-26", "name":"Como"},{"code":"IT-27", "name":"Cremona"},{"code":"IT-28", "name":"Cosenza"},{"code":"IT-29", "name":"Catania"},{"code":"IT-30", "name":"Catanzaro"},{"code":"IT-31", "name":"Enna"},{"code":"IT-32", "name":"Forlì-Cesena"},{"code":"IT-33", "name":"Ferrara"},{"code":"IT-34", "name":"Foggia"},{"code":"IT-35", "name":"Florence"},{"code":"IT-36", "name":"Fermo"},{"code":"IT-37", "name":"Frosinone"},{"code":"IT-38", "name":"Genoa"},{"code":"IT-39", "name":"Gorizia"},{"code":"IT-40", "name":"Grosseto"},{"code":"IT-41", "name":"Imperia"},{"code":"IT-42", "name":"Isernia"},{"code":"IT-43", "name":"Crotone"},{"code":"IT-44", "name":"Lecco"},{"code":"IT-45", "name":"Lecce"},{"code":"IT-46", "name":"Livorno"},{"code":"IT-47", "name":"Lodi"},{"code":"IT-48", "name":"Latina"},{"code":"IT-49", "name":"Lucca"},{"code":"IT-50", "name":"Monza and Brianza"},{"code":"IT-51", "name":"Macerata"},{"code":"IT-52", "name":"Messina"},{"code":"IT-53", "name":"Milan"},{"code":"IT-54", "name":"Mantua"},{"code":"IT-55", "name":"Modena"},{"code":"IT-56", "name":"Massa and Carrara"},{"code":"IT-57", "name":"Matera"},{"code":"IT-58", "name":"Naples"},{"code":"IT-59", "name":"Novara"},{"code":"IT-60", "name":"Nuoro"},{"code":"IT-61", "name":"Ogliastra"},{"code":"IT-62", "name":"Oristano"},{"code":"IT-63", "name":"Olbia-Tempio"},{"code":"IT-64", "name":"Palermo"},{"code":"IT-65", "name":"Piacenza"},{"code":"IT-66", "name":"Padua"},{"code":"IT-67", "name":"Pescara"},{"code":"IT-68", "name":"Perugia"},{"code":"IT-69", "name":"Pisa"},{"code":"IT-70", "name":"Pordenone"},{"code":"IT-71", "name":"Prato"},{"code":"IT-72", "name":"Parma"},{"code":"IT-73", "name":"Pistoia"},{"code":"IT-74", "name":"Pesaro and Urbino"},{"code":"IT-75", "name":"Pavia"},{"code":"IT-76", "name":"Potenza"},{"code":"IT-77", "name":"Ravenna"},{"code":"IT-78", "name":"Reggio Calabria"},{"code":"IT-79", "name":"Reggio Emilia"},{"code":"IT-80", "name":"Ragusa"},{"code":"IT-81", "name":"Rieti"},{"code":"IT-82", "name":"Rome"},{"code":"IT-83", "name":"Rimini"},{"code":"IT-84", "name":"Rovigo"},{"code":"IT-85", "name":"Salerno"},{"code":"IT-86", "name":"Siena"},{"code":"IT-87", "name":"Sondrio"},{"code":"IT-88", "name":"La Spezia"},{"code":"IT-89", "name":"Syracuse"},{"code":"IT-90", "name":"Sassari"},{"code":"IT-91", "name":"Savona"},{"code":"IT-92", "name":"Taranto"},{"code":"IT-93", "name":"Teramo"},{"code":"IT-94", "name":"Trento"},{"code":"IT-95", "name":"Turin"},{"code":"IT-96", "name":"Trapani"},{"code":"IT-97", "name":"Terni"},{"code":"IT-98", "name":"Trieste"},{"code":"IT-99", "name":"Treviso"},{"code":"IT-100", "name":"Udine"},{"code":"IT-101", "name":"Varese"},{"code":"IT-102", "name":"Verbano-Cusio-Ossola"},{"code":"IT-103", "name":"Vercelli"},{"code":"IT-104", "name":"Venice"},{"code":"IT-105", "name":"Vicenza"},{"code":"IT-106", "name":"Verona"},{"code":"IT-107", "name":"Medio Campidano"},{"code":"IT-108", "name":"Viterbo"},{"code":"IT-109", "name":"Vibo Valentia"},
                    ]},
            {"code":"IE", "name":"Ireland", "nameProvinceRegion": "counties","provinces":[
                {"code":"IE-0", "name":"Carlow"},{"code":"IE-1", "name":"Cavan"},{"code":"IE-2", "name":"Clare"},{"code":"IE-3", "name":"Cork"},{"code":"IE-4", "name":"Donegal"},{"code":"IE-5", "name":"Dublin"},{"code":"IE-6", "name":"Galway"},{"code":"IE-7", "name":"Kerry"},{"code":"IE-8", "name":"Kildare"},{"code":"IE-9", "name":"Kilkenny"},{"code":"IE-10", "name":"Laois"},{"code":"IE-11", "name":"Leitrim"},{"code":"IE-12", "name":"Limerick"},{"code":"IE-13", "name":"Longford"},{"code":"IE-14", "name":"Louth"},{"code":"IE-15", "name":"Mayo"},{"code":"IE-16", "name":"Meath"},{"code":"IE-17", "name":"Monaghan"},{"code":"IE-18", "name":"Offaly"},{"code":"IE-19", "name":"Roscommon"},{"code":"IE-20", "name":"Sligo"},{"code":"IE-21", "name":"Tipperary"},{"code":"IE-22", "name":"Waterford"},{"code":"IE-23", "name":"Westmeath"},{"code":"IE-24", "name":"Wexford"},{"code":"IE-25", "name":"Wicklow"},
                    ]},
            {"code":"JE", "name":"Jersey"},
            {"code":"LV", "name":"Latvia"},
            {"code":"LI", "name":"Liechtenstein"},
            {"code":"LT", "name":"Lithuania"},
            {"code":"LU", "name":"Luxembourg"},
            {"code":"MK", "name":"Macedonia"},
            {"code":"MT", "name":"Malta"},
            {"code":"MD", "name":"Moldova"},
            {"code":"MC", "name":"Monaco"},
            {"code":"ME", "name":"Montenegro"},
            {"code":"NL", "name":"Netherlands the"},
            {"code":"NO", "name":"Norway"},
            {"code":"PL", "name":"Poland"},
            {"code":"PT", "name":"Portugal, Portuguese Republic", "nameProvinceRegion": "regions","provinces":[
                            {"code":"PT-0", "name":"Azores"},{"code":"PT-1", "name":"Aveiro"},{"code":"PT-2", "name":"Beja"},{"code":"PT-3", "name":"Braga"},{"code":"PT-4", "name":"Bragança"},{"code":"PT-5", "name":"Castelo Branco"},{"code":"PT-6", "name":"Coimbra"},{"code":"PT-7", "name":"Évora"},{"code":"PT-8", "name":"Faro"},{"code":"PT-9", "name":"Guarda"},{"code":"PT-10", "name":"Leiria"},{"code":"PT-11", "name":"Lisbon"},{"code":"PT-12", "name":"Madeira"},{"code":"PT-13", "name":"Portalegre"},{"code":"PT-14", "name":"Porto"},{"code":"PT-15", "name":"Santarém"},{"code":"PT-16", "name":"Setúbal"},{"code":"PT-17", "name":"Viana do Castelo"},{"code":"PT-18", "name":"Vila Real"},{"code":"PT-19", "name":"Viseu"},
                    ]},
            {"code":"RO", "name":"Romania", "nameProvinceRegion": "counties","provinces":[
                            {"code":"RO-0", "name":"Alba"},{"code":"RO-1", "name":"Arad"},{"code":"RO-2", "name":"Argeș"},{"code":"RO-3", "name":"Bacău"},{"code":"RO-4", "name":"Bihor"},{"code":"RO-5", "name":"Bistriţa-Năsăud"},{"code":"RO-6", "name":"Botoşani"},{"code":"RO-7", "name":"Brăila"},{"code":"RO-8", "name":"Braşov"},{"code":"RO-9", "name":"Bucharest"},{"code":"RO-10", "name":"Buzău"},{"code":"RO-11", "name":"Caraș-Severin"},{"code":"RO-12", "name":"Cluj"},{"code":"RO-13", "name":"Constanța"},{"code":"RO-14", "name":"Covasna"},{"code":"RO-15", "name":"Călărași"},{"code":"RO-16", "name":"Dolj"},{"code":"RO-17", "name":"Dâmbovița"},{"code":"RO-18", "name":"Galați"},{"code":"RO-19", "name":"Giurgiu"},{"code":"RO-20", "name":"Gorj"},{"code":"RO-21", "name":"Harghita"},{"code":"RO-22", "name":"Hunedoara"},{"code":"RO-23", "name":"Ialomița"},{"code":"RO-24", "name":"Iași"},{"code":"RO-25", "name":"Ilfov"},{"code":"RO-26", "name":"Maramureş"},{"code":"RO-27", "name":"Mehedinți"},{"code":"RO-28", "name":"Mureş"},{"code":"RO-29", "name":"Neamţ"},{"code":"RO-30", "name":"Olt"},{"code":"RO-31", "name":"Prahova"},{"code":"RO-32", "name":"Sălaj"},{"code":"RO-33", "name":"Satu Mare"},{"code":"RO-34", "name":"Sibiu"},{"code":"RO-35", "name":"Suceava"},{"code":"RO-36", "name":"Teleorman"},{"code":"RO-37", "name":"Timiș"},{"code":"RO-38", "name":"Tulcea"},{"code":"RO-39", "name":"Vâlcea"},{"code":"RO-40", "name":"Vaslui"},{"code":"RO-41", "name":"Vrancea"},
                    ]},
            {"code":"RU", "name":"Russian Federation", "nameProvinceRegion": "regions","provinces":[
                            {"code":"RU-0", "name":"Altai Krai"},{"code":"RU-1", "name":"Altai"},{"code":"RU-2", "name":"Amur"},{"code":"RU-3", "name":"Arkhangelsk"},{"code":"RU-4", "name":"Astrakhan"},{"code":"RU-5", "name":"Belgorod"},{"code":"RU-6", "name":"Bryansk"},{"code":"RU-7", "name":"Chechen"},{"code":"RU-8", "name":"Chelyabinsk"},{"code":"RU-9", "name":"Chukotka Okrug"},{"code":"RU-10", "name":"Chuvash"},{"code":"RU-11", "name":"Irkutsk"},{"code":"RU-12", "name":"Ivanovo"},{"code":"RU-13", "name":"Jewish"},{"code":"RU-14", "name":"Kabardino-Balkar"},{"code":"RU-15", "name":"Kaliningrad"},{"code":"RU-16", "name":"Kaluga"},{"code":"RU-17", "name":"Kamchatka Krai"},{"code":"RU-18", "name":"Karachay-Cherkess"},{"code":"RU-19", "name":"Kemerovo"},{"code":"RU-20", "name":"Khabarovsk Krai"},{"code":"RU-21", "name":"Khanty-Mansi"},{"code":"RU-22", "name":"Kirov"},{"code":"RU-23", "name":"Komi"},{"code":"RU-24", "name":"Kostroma"},{"code":"RU-25", "name":"Krasnodar Krai"},{"code":"RU-26", "name":"Krasnoyarsk Krai"},{"code":"RU-27", "name":"Kurgan"},{"code":"RU-28", "name":"Kursk"},{"code":"RU-29", "name":"Leningrad"},{"code":"RU-30", "name":"Lipetsk"},{"code":"RU-31", "name":"Magadan"},{"code":"RU-32", "name":"Mari El"},{"code":"RU-33", "name":"Moscow"},{"code":"RU-34", "name":"Moscow Province"},{"code":"RU-35", "name":"Murmansk"},{"code":"RU-36", "name":"Nizhny Novgorod"},{"code":"RU-37", "name":"Novgorod"},{"code":"RU-38", "name":"Novosibirsk"},{"code":"RU-39", "name":"Omsk"},{"code":"RU-40", "name":"Orenburg"},{"code":"RU-41", "name":"Oryol"},{"code":"RU-42", "name":"Penza"},{"code":"RU-43", "name":"Perm Krai"},{"code":"RU-44", "name":"Primorsky Krai"},{"code":"RU-45", "name":"Pskov"},{"code":"RU-46", "name":"Adygea"},{"code":"RU-47", "name":"Bashkortostan"},{"code":"RU-48", "name":"Buryat"},{"code":"RU-49", "name":"Dagestan"},{"code":"RU-50", "name":"Ingushetia"},{"code":"RU-51", "name":"Kalmykia"},{"code":"RU-52", "name":"Karelia"},{"code":"RU-53", "name":"Khakassia"},{"code":"RU-54", "name":"Mordovia"},{"code":"RU-55", "name":"North Ossetia-Alania"},{"code":"RU-56", "name":"Tatarstan"},{"code":"RU-57", "name":"Rostov"},{"code":"RU-58", "name":"Ryazan"},{"code":"RU-59", "name":"Saint Petersburg"},{"code":"RU-60", "name":"Sakha"},{"code":"RU-61", "name":"Sakhalin"},{"code":"RU-62", "name":"Samara"},{"code":"RU-63", "name":"Saratov"},{"code":"RU-64", "name":"Smolensk"},{"code":"RU-65", "name":"Stavropol Krai"},{"code":"RU-66", "name":"Sverdlovsk"},{"code":"RU-67", "name":"Tambov"},{"code":"RU-68", "name":"Tomsk"},{"code":"RU-69", "name":"Tula"},{"code":"RU-70", "name":"Tver"},{"code":"RU-71", "name":"Tyumen"},{"code":"RU-72", "name":"Tuva"},{"code":"RU-73", "name":"Udmurt"},{"code":"RU-74", "name":"Ulyanovsk"},{"code":"RU-75", "name":"Vladimir"},{"code":"RU-76", "name":"Volgograd"},{"code":"RU-77", "name":"Vologda"},{"code":"RU-78", "name":"Voronezh"},{"code":"RU-79", "name":"Yamalo-Nenets Okrug"},{"code":"RU-80", "name":"Yaroslavl"},{"code":"RU-81", "name":"Zabaykalsky Krai"},
                    ]},
            {"code":"SM", "name":"San Marino"},
            {"code":"RS", "name":"Serbia"},
            {"code":"SK", "name":"Slovakia (Slovak Republic)"},
            {"code":"SI", "name":"Slovenia"},
            {"code":"ES", "name":"Spain", "nameProvinceRegion": "provinces","provinces":[
                            {"code":"ES-0", "name":"A Coruña"},{"code":"ES-1", "name":"Álava"},{"code":"ES-2", "name":"Albacete"},{"code":"ES-3", "name":"Alicante"},{"code":"ES-4", "name":"Almería"},{"code":"ES-5", "name":"Asturias Province"},{"code":"ES-6", "name":"Ávila"},{"code":"ES-7", "name":"Badajoz"},{"code":"ES-8", "name":"Balears Province"},{"code":"ES-9", "name":"Barcelona"},{"code":"ES-10", "name":"Burgos"},{"code":"ES-11", "name":"Cáceres"},{"code":"ES-12", "name":"Cádiz"},{"code":"ES-13", "name":"Cantabria Province"},{"code":"ES-14", "name":"Castellón"},{"code":"ES-15", "name":"Ceuta"},{"code":"ES-16", "name":"Ciudad Real"},{"code":"ES-17", "name":"Córdoba"},{"code":"ES-18", "name":"Cuenca"},{"code":"ES-19", "name":"Girona"},{"code":"ES-20", "name":"Granada"},{"code":"ES-21", "name":"Guadalajara"},{"code":"ES-22", "name":"Gipuzkoa"},{"code":"ES-23", "name":"Huelva"},{"code":"ES-24", "name":"Huesca"},{"code":"ES-25", "name":"Jaén"},{"code":"ES-26", "name":"La Rioja Province"},{"code":"ES-27", "name":"Las Palmas"},{"code":"ES-28", "name":"León"},{"code":"ES-29", "name":"Lleida"},{"code":"ES-30", "name":"Lugo"},{"code":"ES-31", "name":"Madrid Province"},{"code":"ES-32", "name":"Málaga"},{"code":"ES-33", "name":"Melilla"},{"code":"ES-34", "name":"Murcia"},{"code":"ES-35", "name":"Navarra"},{"code":"ES-36", "name":"Ourense"},{"code":"ES-37", "name":"Palencia"},{"code":"ES-38", "name":"Pontevedra"},{"code":"ES-39", "name":"Salamanca"},{"code":"ES-40", "name":"Santa Cruz de Tenerife"},{"code":"ES-41", "name":"Segovia"},{"code":"ES-42", "name":"Seville"},{"code":"ES-43", "name":"Soria"},{"code":"ES-44", "name":"Tarragona"},{"code":"ES-45", "name":"Teruel"},{"code":"ES-46", "name":"Toledo"},{"code":"ES-47", "name":"Valencia"},{"code":"ES-48", "name":"Valladolid"},{"code":"ES-49", "name":"Biscay"},{"code":"ES-50", "name":"Zamora"},{"code":"ES-51", "name":"Zaragoza"},
                    ]},
            {"code":"SE", "name":"Sweden"},
            {"code":"CH", "name":"Switzerland, Swiss Confederation"},
            {"code":"SJ", "name":"Svalbard & Jan Mayen Islands"},
            {"code":"TR", "name":"Turkey"},
            {"code":"UA", "name":"Ukraine"},
            {"code":"GB", "name":"United Kingdom", "nameProvinceRegion": "regions","provinces":[
                            {"code":"GB-0", "name":"British Forces"},{"code":"GB-1", "name":"England"},{"code":"GB-2", "name":"Northern Ireland"},{"code":"GB-3", "name":"Scotland"},{"code":"GB-4", "name":"Wales"},
                    ]},
            {"code":"VA", "name":"Vatican City"}
        ] },
    { 'continent': 'NO', 'names': [
            {"code":"AG", "name":"Antigua and Barbuda"},
            {"code":"AI", "name":"Anguilla"},
            {"code":"AW", "name":"Aruba"},
            {"code":"BB", "name":"Barbados"},
            {"code":"BM", "name":"Bermuda"},
            {"code":"BS", "name":"Bahamas the"},
            {"code":"BZ", "name":"Belize"},
            {"code":"VG", "name":"British Virgin Islands"},
            {"code":"CA", "name":"Canada", "nameProvinceRegion": "provinces","provinces":[
                            {"code":"CA-0", "name":"Alberta"},{"code":"CA-1", "name":"British Columbia"},{"code":"CA-2", "name":"Manitoba"},{"code":"CA-3", "name":"New Brunswick"},{"code":"CA-4", "name":"Newfoundland and Labrador"},{"code":"CA-5", "name":"Northwest Territories"},{"code":"CA-6", "name":"Nova Scotia"},{"code":"CA-7", "name":"Nunavut"},{"code":"CA-8", "name":"Ontario"},{"code":"CA-9", "name":"Prince Edward Island"},{"code":"CA-10", "name":"Quebec"},{"code":"CA-11", "name":"Saskatchewan"},{"code":"CA-12", "name":"Yukon"},
                    ]},
            {"code":"KY", "name":"Cayman Islands"},
            {"code":"CR", "name":"Costa Rica"},
            {"code":"CU", "name":"Cuba"},
            {"code":"DM", "name":"Dominica"},
            {"code":"DO", "name":"Dominican Republic"},
            {"code":"SV", "name":"El Salvador"},
            {"code":"GD", "name":"Grenada"},
            {"code":"GL", "name":"Greenland"},
            {"code":"GP", "name":"Guadeloupe"},
            {"code":"GT", "name":"Guatemala", "nameProvinceRegion": "regions","provinces":[
                            {"code":"GT-0", "name":"Alta Verapaz"},{"code":"GT-1", "name":"Baja Verapaz"},{"code":"GT-2", "name":"Chimaltenango"},{"code":"GT-3", "name":"Chiquimula"},{"code":"GT-4", "name":"El Progreso"},{"code":"GT-5", "name":"Escuintla"},{"code":"GT-6", "name":"Guatemala"},{"code":"GT-7", "name":"Huehuetenango"},{"code":"GT-8", "name":"Izabal"},{"code":"GT-9", "name":"Jalapa"},{"code":"GT-10", "name":"Jutiapa"},{"code":"GT-11", "name":"Petén"},{"code":"GT-12", "name":"Quetzaltenango"},{"code":"GT-13", "name":"Quiché"},{"code":"GT-14", "name":"Retalhuleu"},{"code":"GT-15", "name":"Sacatepéquez"},{"code":"GT-16", "name":"San Marcos"},{"code":"GT-17", "name":"Santa Rosa"},{"code":"GT-18", "name":"Sololá"},{"code":"GT-19", "name":"Suchitepéquez"},{"code":"GT-20", "name":"Totonicapán"},{"code":"GT-21", "name":"Zacapa"},
                    ]},
            {"code":"HN", "name":"Honduras"},
            {"code":"HT", "name":"Haiti"},
            {"code":"JM", "name":"Jamaica"},
            {"code":"MQ", "name":"Martinique"},
            {"code":"MS", "name":"Montserrat"},
            {"code":"MX", "name":"Mexico", "nameProvinceRegion": "states","provinces":[
                            {"code":"MX-0", "name":"Aguascalientes"},{"code":"MX-1", "name":"Baja California"},{"code":"MX-2", "name":"Baja California Sur"},{"code":"MX-3", "name":"Campeche"},{"code":"MX-4", "name":"Chiapas"},{"code":"MX-5", "name":"Chihuahua"},{"code":"MX-6", "name":"Ciudad de Mexico"},{"code":"MX-7", "name":"Coahuila"},{"code":"MX-8", "name":"Colima"},{"code":"MX-9", "name":"Durango"},{"code":"MX-10", "name":"Guanajuato"},{"code":"MX-11", "name":"Guerrero"},{"code":"MX-12", "name":"Hidalgo"},{"code":"MX-13", "name":"Jalisco"},{"code":"MX-14", "name":"Mexico State"},{"code":"MX-15", "name":"Michoacán"},{"code":"MX-16", "name":"Morelos"},{"code":"MX-17", "name":"Nayarit"},{"code":"MX-18", "name":"Nuevo León"},{"code":"MX-19", "name":"Oaxaca"},{"code":"MX-20", "name":"Puebla"},{"code":"MX-21", "name":"Querétaro"},{"code":"MX-22", "name":"Quintana Roo"},{"code":"MX-23", "name":"San Luis Potosí"},{"code":"MX-24", "name":"Sinaloa"},{"code":"MX-25", "name":"Sonora"},{"code":"MX-26", "name":"Tabasco"},{"code":"MX-27", "name":"Tamaulipas"},{"code":"MX-28", "name":"Tlaxcala"},{"code":"MX-29", "name":"Veracruz"},{"code":"MX-30", "name":"Yucatán"},{"code":"MX-31", "name":"Zacatecas"},
                    ]},
            {"code":"AN", "name":"Netherlands Antilles"},
            {"code":"NI", "name":"Nicaragua"},
            {"code":"PA", "name":"Panama", "nameProvinceRegion": "regions","provinces":[
                            {"code":"PA-0", "name":"Bocas del Toro"},{"code":"PA-1", "name":"Chiriquí"},{"code":"PA-2", "name":"Coclé"},{"code":"PA-3", "name":"Colón"},{"code":"PA-4", "name":"Darién"},{"code":"PA-5", "name":"Emberá"},{"code":"PA-6", "name":"Herrera"},{"code":"PA-7", "name":"Guna Yala"},{"code":"PA-8", "name":"Los Santos"},{"code":"PA-9", "name":"Ngöbe-Buglé"},{"code":"PA-10", "name":"Panamá"},{"code":"PA-11", "name":"West Panamá"},{"code":"PA-12", "name":"Veraguas"},
                    ]},
            {"code":"PR", "name":"Puerto Rico"},
            {"code":"PM", "name":"Saint Pierre and Miquelon"},
            {"code":"BL", "name":"Saint Barthelemy"},
            {"code":"KN", "name":"Saint Kitts and Nevis"},
            {"code":"LC", "name":"Saint Lucia"},
            {"code":"MF", "name":"Saint Martin"},
            {"code":"VC", "name":"Saint Vincent and the Grenadines"},
            {"code":"TT", "name":"Trinidad and Tobago"},
            {"code":"TC", "name":"Turks and Caicos Islands"},
            {"code":"US", "name":"United States of America", "nameProvinceRegion": "states","provinces":[
                            {"code":"US-0", "name":"Alabama"},{"code":"US-1", "name":"Alaska"},{"code":"US-2", "name":"American Samoa"},{"code":"US-3", "name":"Arizona"},{"code":"US-4", "name":"Arkansas"},{"code":"US-5", "name":"California"},{"code":"US-6", "name":"Colorado"},{"code":"US-7", "name":"Connecticut"},{"code":"US-8", "name":"Delaware"},{"code":"US-9", "name":"Washington DC"},{"code":"US-10", "name":"Micronesia"},{"code":"US-11", "name":"Florida"},{"code":"US-12", "name":"Georgia"},{"code":"US-13", "name":"Guam"},{"code":"US-14", "name":"Hawaii"},{"code":"US-15", "name":"Idaho"},{"code":"US-16", "name":"Illinois"},{"code":"US-17", "name":"Indiana"},{"code":"US-18", "name":"Iowa"},{"code":"US-19", "name":"Kansas"},{"code":"US-20", "name":"Kentucky"},{"code":"US-21", "name":"Louisiana"},{"code":"US-22", "name":"Maine"},{"code":"US-23", "name":"Marshall Islands"},{"code":"US-24", "name":"Maryland"},{"code":"US-25", "name":"Massachusetts"},{"code":"US-26", "name":"Michigan"},{"code":"US-27", "name":"Minnesota"},{"code":"US-28", "name":"Mississippi"},{"code":"US-29", "name":"Missouri"},{"code":"US-30", "name":"Montana"},{"code":"US-31", "name":"Nebraska"},{"code":"US-32", "name":"Nevada"},{"code":"US-33", "name":"New Hampshire"},{"code":"US-34", "name":"New Jersey"},{"code":"US-35", "name":"New Mexico"},{"code":"US-36", "name":"New York"},{"code":"US-37", "name":"North Carolina"},{"code":"US-38", "name":"North Dakota"},{"code":"US-39", "name":"Northern Mariana Islands"},{"code":"US-40", "name":"Ohio"},{"code":"US-41", "name":"Oklahoma"},{"code":"US-42", "name":"Oregon"},{"code":"US-43", "name":"Palau"},{"code":"US-44", "name":"Pennsylvania"},{"code":"US-45", "name":"Puerto Rico"},{"code":"US-46", "name":"Rhode Island"},{"code":"US-47", "name":"South Carolina"},{"code":"US-48", "name":"South Dakota"},{"code":"US-49", "name":"Tennessee"},{"code":"US-50", "name":"Texas"},{"code":"US-51", "name":"Utah"},{"code":"US-52", "name":"Vermont"},{"code":"US-53", "name":"U.S. Virgin Islands"},{"code":"US-54", "name":"Virginia"},{"code":"US-55", "name":"Washington"},{"code":"US-56", "name":"West Virginia"},{"code":"US-57", "name":"Wisconsin"},{"code":"US-58", "name":"Wyoming"},{"code":"US-59", "name":"Armed Forces Americas"},{"code":"US-60", "name":"Armed Forces Europe"},{"code":"US-61", "name":"Armed Forces Pacific"},{"code":"US-62", "name":"United States Virgin Islands"},
        ]},
        ] },
    { 'continent': 'OC', 'names': [
            {"code":"AS", "name":"American Samoa"},
            {"code":"AU", "name":"Australia", "nameProvinceRegion": "states and territories","provinces":[
                            {"code":"AU-0", "name":"Australian Capital Territory"},{"code":"AU-1", "name":"New South Wales"},{"code":"AU-2", "name":"Northern Territory"},{"code":"AU-3", "name":"Queensland"},{"code":"AU-4", "name":"South Australia"},{"code":"AU-5", "name":"Tasmania"},{"code":"AU-6", "name":"Victoria"},{"code":"AU-7", "name":"Western Australia"},
                    ]},
            {"code":"CK", "name":"Cook Islands"},
            {"code":"FJ", "name":"Fiji the Fiji Islands"},
            {"code":"PF", "name":"French Polynesia"},
            {"code":"GU", "name":"Guam"},
            {"code":"KI", "name":"Kiribati"},
            {"code":"MH", "name":"Marshall Islands"},
            {"code":"FM", "name":"Micronesia"},
            {"code":"NR", "name":"Nauru"},
            {"code":"NC", "name":"New Caledonia"},
            {"code":"NZ", "name":"New Zealand", "nameProvinceRegion": "regions","provinces":[
                            {"code":"NZ-0", "name":"Auckland"},{"code":"NZ-1", "name":"Bay of Plenty"},{"code":"NZ-2", "name":"Canterbury"},{"code":"NZ-3", "name":"Chatham Islands"},{"code":"NZ-4", "name":"Gisborne"},{"code":"NZ-5", "name":"Hawke’s Bay"},{"code":"NZ-6", "name":"Manawatu-Wanganui"},{"code":"NZ-7", "name":"Marlborough"},{"code":"NZ-8", "name":"Nelson"},{"code":"NZ-9", "name":"Northland"},{"code":"NZ-10", "name":"Otago"},{"code":"NZ-11", "name":"Southland"},{"code":"NZ-12", "name":"Taranaki"},{"code":"NZ-13", "name":"Tasman"},{"code":"NZ-14", "name":"Waikato"},{"code":"NZ-15", "name":"Wellington"},{"code":"NZ-16", "name":"West Coast"},
                    ]},
            {"code":"NU", "name":"Niue"},
            {"code":"NF", "name":"Norfolk Island"},
            {"code":"MP", "name":"Northern Mariana Islands"},
            {"code":"PW", "name":"Palau"},
            {"code":"PG", "name":"Papua New Guinea"},
            {"code":"PN", "name":"Pitcairn Islands"},
            {"code":"WS", "name":"Samoa"},
            {"code":"SB", "name":"Solomon Islands"},
            {"code":"TK", "name":"Tokelau"},
            {"code":"TO", "name":"Tonga"},
            {"code":"TV", "name":"Tuvalu"},
            {"code":"UM", "name":"United States Minor Outlying Islands"},
            {"code":"VU", "name":"Vanuatu"},
            {"code":"WF", "name":"Wallis and Futuna"},
    ] },
    { 'continent': 'SO', 'names': [
        {"code": "AR", "name": "Argentina", "nameProvinceRegion": "provinces", "provinces": [
                        {"code":"AR-0", "name":"Buenos Aires Province"},{"code":"AR-1", "name":"Catamarca"},{"code":"AR-2", "name":"Chaco"},{"code":"AR-3", "name":"Chubut"},{"code":"AR-4", "name":"Buenos Aires (Autonomous City)"},{"code":"AR-5", "name":"Córdoba"},{"code":"AR-6", "name":"Corrientes"},{"code":"AR-7", "name":"Entre Ríos"},{"code":"AR-8", "name":"Formosa"},{"code":"AR-9", "name":"Jujuy"},{"code":"AR-10", "name":"La Pampa"},{"code":"AR-11", "name":"La Rioja"},{"code":"AR-12", "name":"Mendoza"},{"code":"AR-13", "name":"Misiones"},{"code":"AR-14", "name":"Neuquén"},{"code":"AR-15", "name":"Río Negro"},{"code":"AR-16", "name":"Salta"},{"code":"AR-17", "name":"San Juan"},{"code":"AR-18", "name":"San Luis"},{"code":"AR-19", "name":"Santa Cruz"},{"code":"AR-20", "name":"Santa Fe"},{"code":"AR-21", "name":"Santiago del Estero"},{"code":"AR-22", "name":"Tierra del Fuego"},{"code":"AR-23", "name":"Tucumán"},
            ]},
        {"code": "BO", "name": "Bolivia"},
        {"code": "BR", "name": "Brazil", "nameProvinceRegion": "states", "provinces": [
                        {"code":"BR-0", "name":"Acre"},{"code":"BR-1", "name":"Alagoas"},{"code":"BR-2", "name":"Amapá"},{"code":"BR-3", "name":"Amazonas"},{"code":"BR-4", "name":"Bahia"},{"code":"BR-5", "name":"Ceará"},{"code":"BR-6", "name":"Federal District"},{"code":"BR-7", "name":"Espírito Santo"},{"code":"BR-8", "name":"Goiás"},{"code":"BR-9", "name":"Maranhão"},{"code":"BR-10", "name":"Mato Grosso"},{"code":"BR-11", "name":"Mato Grosso do Sul"},{"code":"BR-12", "name":"Minas Gerais"},{"code":"BR-13", "name":"Pará"},{"code":"BR-14", "name":"Paraíba"},{"code":"BR-15", "name":"Paraná"},{"code":"BR-16", "name":"Pernambuco"},{"code":"BR-17", "name":"Piauí"},{"code":"BR-18", "name":"Rio Grande do Norte"},{"code":"BR-19", "name":"Rio Grande do Sul"},{"code":"BR-20", "name":"Rio de Janeiro"},{"code":"BR-21", "name":"Rondônia"},{"code":"BR-22", "name":"Roraima"},{"code":"BR-23", "name":"Santa Catarina"},{"code":"BR-24", "name":"São Paulo"},{"code":"BR-25", "name":"Sergipe"},{"code":"BR-26", "name":"Tocantins"},
            ]},
        {"code": "CL", "name": "Chile", "nameProvinceRegion": "regions", "provinces": [
                        {"code":"CL-0", "name":"Arica y Parinacota"},{"code":"CL-1", "name":"Tarapacá"},{"code":"CL-2", "name":"Antofagasta"},{"code":"CL-3", "name":"Atacama"},{"code":"CL-4", "name":"Coquimbo"},{"code":"CL-5", "name":"Valparaíso"},{"code":"CL-6", "name":"Santiago Metropolitan"},{"code":"CL-7", "name":"Libertador General Bernardo O’Higgins"},{"code":"CL-8", "name":"Maule"},{"code":"CL-9", "name":"Ñuble"},{"code":"CL-10", "name":"Bío Bío"},{"code":"CL-11", "name":"Araucanía"},{"code":"CL-12", "name":"Los Ríos"},{"code":"CL-13", "name":"Los Lagos"},{"code":"CL-14", "name":"Aysén"},{"code":"CL-15", "name":"Magallanes Region"},
            ]},
        {"code": "CO", "name": "Colombia", "nameProvinceRegion": "provinces", "provinces": [
                        {"code":"CO-0", "name":"Capital District"},{"code":"CO-1", "name":"Amazonas"},{"code":"CO-2", "name":"Antioquia"},{"code":"CO-3", "name":"Arauca"},{"code":"CO-4", "name":"Atlántico"},{"code":"CO-5", "name":"Bolívar"},{"code":"CO-6", "name":"Boyacá"},{"code":"CO-7", "name":"Caldas"},{"code":"CO-8", "name":"Caquetá"},{"code":"CO-9", "name":"Casanare"},{"code":"CO-10", "name":"Cauca"},{"code":"CO-11", "name":"Cesar"},{"code":"CO-12", "name":"Chocó"},{"code":"CO-13", "name":"Córdoba"},{"code":"CO-14", "name":"Cundinamarca"},{"code":"CO-15", "name":"Guainía"},{"code":"CO-16", "name":"Guaviare"},{"code":"CO-17", "name":"Huila"},{"code":"CO-18", "name":"La Guajira"},{"code":"CO-19", "name":"Magdalena"},{"code":"CO-20", "name":"Meta"},{"code":"CO-21", "name":"Nariño"},{"code":"CO-22", "name":"Norte de Santander"},{"code":"CO-23", "name":"Putumayo"},{"code":"CO-24", "name":"Quindío"},{"code":"CO-25", "name":"Risaralda"},{"code":"CO-26", "name":"San Andrés & Providencia"},{"code":"CO-27", "name":"Santander"},{"code":"CO-28", "name":"Sucre"},{"code":"CO-29", "name":"Tolima"},{"code":"CO-30", "name":"Valle del Cauca"},{"code":"CO-31", "name":"Vaupés"},{"code":"CO-32", "name":"Vichada"},
            ]},
        {"code": "EC", "name": "Ecuador"},
        {"code": "FK", "name": "Falkland Islands (Malvinas)"},
        {"code": "GF", "name": "French Guiana"},
        {"code": "GY", "name": "Guyana"},
        {"code": "PE", "name": "Peru", "nameProvinceRegion": "regions", "provinces": [
                        {"code":"PE-0", "name":"Amazonas"},{"code":"PE-1", "name":"Ancash"},{"code":"PE-2", "name":"Apurímac"},{"code":"PE-3", "name":"Arequipa"},{"code":"PE-4", "name":"Ayacucho"},{"code":"PE-5", "name":"Cajamarca"},{"code":"PE-6", "name":"El Callao"},{"code":"PE-7", "name":"Cusco"},{"code":"PE-8", "name":"Huancavelica"},{"code":"PE-9", "name":"Huánuco"},{"code":"PE-10", "name":"Ica"},{"code":"PE-11", "name":"Junín"},{"code":"PE-12", "name":"La Libertad"},{"code":"PE-13", "name":"Lambayeque"},{"code":"PE-14", "name":"Lima Region"},{"code":"PE-15", "name":"Lima"},{"code":"PE-16", "name":"Loreto"},{"code":"PE-17", "name":"Madre de Dios"},{"code":"PE-18", "name":"Moquegua"},{"code":"PE-19", "name":"Pasco"},{"code":"PE-20", "name":"Piura"},{"code":"PE-21", "name":"Puno"},{"code":"PE-22", "name":"San Martín"},{"code":"PE-23", "name":"Tacna"},{"code":"PE-24", "name":"Tumbes"},{"code":"PE-25", "name":"Ucayali"},
            ]},
        {"code": "PY", "name": "Paraguay"},
        {"code": "SR", "name": "Suriname"},
        {"code": "UY", "name": "Uruguay, Eastern Republic of"},
        {"code": "VE", "name": "Venezuela"}
        ]
    }
    ]
